-- MySQL Script generated by MySQL Workbench
-- Sat Jun 30 16:36:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema rede_social
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rede_social` ;

-- -----------------------------------------------------
-- Schema rede_social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rede_social` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `rede_social` ;

-- -----------------------------------------------------
-- Table `rede_social`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rede_social`.`pessoa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rede_social`.`pessoa` (
  `idpessoa` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rede_social`.`postagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rede_social`.`postagem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rede_social`.`postagem` (
  `idpostagem` INT(11) NOT NULL AUTO_INCREMENT,
  `postagem` LONGTEXT NULL DEFAULT NULL,
  `fkid_pessoa` INT(11) NOT NULL,
  PRIMARY KEY (`idpostagem`),
  CONSTRAINT `fk_pessoa_postagem`
    FOREIGN KEY (`fkid_pessoa`)
    REFERENCES `rede_social`.`pessoa` (`idpessoa`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_pessoa_postagem_idx` ON `rede_social`.`postagem` (`fkid_pessoa` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rede_social`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rede_social`.`comentario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rede_social`.`comentario` (
  `idcomentario` INT(11) NOT NULL AUTO_INCREMENT,
  `fkid_postagem` INT(11) NOT NULL,
  `fkid_pessoa` INT(11) NOT NULL,
  PRIMARY KEY (`idcomentario`),
  CONSTRAINT `fk_comentario_pessoa`
    FOREIGN KEY (`fkid_pessoa`)
    REFERENCES `rede_social`.`pessoa` (`idpessoa`),
  CONSTRAINT `fk_comentario_postagem`
    FOREIGN KEY (`fkid_postagem`)
    REFERENCES `rede_social`.`postagem` (`idpostagem`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_comentario_postagem_idx` ON `rede_social`.`comentario` (`fkid_postagem` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comentario_pessoa_idx` ON `rede_social`.`comentario` (`fkid_pessoa` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rede_social`.`compartilhamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rede_social`.`compartilhamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rede_social`.`compartilhamento` (
  `idcompartilhamento` INT(11) NOT NULL AUTO_INCREMENT,
  `fkid_postagem` INT(11) NOT NULL,
  `fkid_pessoa` INT(11) NOT NULL,
  PRIMARY KEY (`idcompartilhamento`),
  CONSTRAINT `fk_compartilhamento_pessoa`
    FOREIGN KEY (`fkid_pessoa`)
    REFERENCES `rede_social`.`pessoa` (`idpessoa`),
  CONSTRAINT `fk_compartilhamento_postagem`
    FOREIGN KEY (`fkid_postagem`)
    REFERENCES `rede_social`.`postagem` (`idpostagem`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_compartilhamento_postagem_idx` ON `rede_social`.`compartilhamento` (`fkid_postagem` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_compartilhamento_pessoa_idx` ON `rede_social`.`compartilhamento` (`fkid_pessoa` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rede_social`.`curtiu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rede_social`.`curtiu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rede_social`.`curtiu` (
  `idlike` INT(11) NOT NULL AUTO_INCREMENT,
  `fkid_postagem` INT(11) NOT NULL,
  `fkid_pessoa` INT(11) NOT NULL,
  PRIMARY KEY (`idlike`),
  CONSTRAINT `fk_like_pessoa`
    FOREIGN KEY (`fkid_pessoa`)
    REFERENCES `rede_social`.`pessoa` (`idpessoa`),
  CONSTRAINT `fk_like_postagem`
    FOREIGN KEY (`fkid_postagem`)
    REFERENCES `rede_social`.`postagem` (`idpostagem`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_like_postagem_idx` ON `rede_social`.`curtiu` (`fkid_postagem` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_like_pessoa_idx` ON `rede_social`.`curtiu` (`fkid_pessoa` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rede_social`.`pessoa_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rede_social`.`pessoa_permissao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rede_social`.`pessoa_permissao` (
  `idpessoa_permissao` INT(11) NOT NULL AUTO_INCREMENT,
  `fkidpessoa` INT(11) NOT NULL,
  `fkidpessoa_no_perfil` INT(11) NOT NULL,
  `ver_perfil` TINYINT(4) NOT NULL DEFAULT '1',
  `postar_no_perfil` TINYINT(4) NOT NULL DEFAULT '1',
  `comentar_no_perfil` TINYINT(4) NOT NULL DEFAULT '1',
  `dar_like_na_postagem` TINYINT(4) NOT NULL DEFAULT '1',
  `compartilhar_postagem` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idpessoa_permissao`),
  CONSTRAINT `fkid_permissao_pessoa`
    FOREIGN KEY (`fkidpessoa`)
    REFERENCES `rede_social`.`pessoa` (`idpessoa`),
  CONSTRAINT `fkid_pessoa_permissao`
    FOREIGN KEY (`fkidpessoa`)
    REFERENCES `rede_social`.`pessoa` (`idpessoa`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fkid_pessoa_idx` ON `rede_social`.`pessoa_permissao` (`fkidpessoa` ASC);

SHOW WARNINGS;
USE `rede_social` ;

-- -----------------------------------------------------
-- Placeholder table for view `rede_social`.`exerciciohardcore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social`.`exerciciohardcore` (`idpostagem` INT, `postagem` INT, `fkid_pessoa` INT, `Quem Curtiu` INT, `Quem Compartilhou` INT, `Quem Comentou` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `rede_social`.`exerciciohardcore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rede_social`.`exerciciohardcore`;
SHOW WARNINGS;
DROP VIEW IF EXISTS `rede_social`.`exerciciohardcore` ;
SHOW WARNINGS;
USE `rede_social`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `rede_social`.`exerciciohardcore` AS select `rede_social`.`postagem`.`idpostagem` AS `idpostagem`,`rede_social`.`postagem`.`postagem` AS `postagem`,`rede_social`.`postagem`.`fkid_pessoa` AS `fkid_pessoa`,`quem_curtiu`.`nome` AS `Quem Curtiu`,`quem_compartilhou`.`nome` AS `Quem Compartilhou`,`quem_comentou`.`nome` AS `Quem Comentou` from (((`rede_social`.`postagem` left join (select distinct `rede_social`.`pessoa`.`nome` AS `nome`,`rede_social`.`curtiu`.`fkid_postagem` AS `fkid_postagem` from (`rede_social`.`curtiu` join `rede_social`.`pessoa` on((`rede_social`.`pessoa`.`idpessoa` = `rede_social`.`curtiu`.`fkid_pessoa`)))) `quem_curtiu` on((`quem_curtiu`.`fkid_postagem` = `rede_social`.`postagem`.`idpostagem`))) left join (select distinct `rede_social`.`pessoa`.`nome` AS `nome`,`rede_social`.`compartilhamento`.`fkid_postagem` AS `fkid_postagem` from (`rede_social`.`compartilhamento` join `rede_social`.`pessoa` on((`rede_social`.`pessoa`.`idpessoa` = `rede_social`.`compartilhamento`.`fkid_pessoa`)))) `quem_compartilhou` on((`quem_compartilhou`.`fkid_postagem` = `rede_social`.`postagem`.`idpostagem`))) left join (select distinct `rede_social`.`pessoa`.`nome` AS `nome`,`rede_social`.`comentario`.`fkid_postagem` AS `fkid_postagem` from (`rede_social`.`comentario` join `rede_social`.`pessoa` on((`rede_social`.`pessoa`.`idpessoa` = `rede_social`.`comentario`.`fkid_pessoa`)))) `quem_comentou` on((`quem_comentou`.`fkid_postagem` = `rede_social`.`postagem`.`idpostagem`))) order by `rede_social`.`postagem`.`idpostagem`;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
